### ISSUE TITLE
Add tests against oldest possible dependencies

### ISSUE THREAD

**Issue by enl** [enl/flysystem-cloudinary#31]
I can just copy these parts from flysystem's travis config:

```yaml
env:
  - COMPOSER_OPTS=""
  - COMPOSER_OPTS="--prefer-lowest"

install:
  - travis_retry composer update --prefer-dist $COMPOSER_OPTS
```
